export const COUNTRY_CODES_EN = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albania" },
    { code: "DZ", name: "Algeria" },
    { code: "AD", name: "Andorra" },
    { code: "AO", name: "Angola" },
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "AR", name: "Argentina" },
    { code: "AM", name: "Armenia" },
    { code: "AU", name: "Australia" },
    { code: "AT", name: "Austria" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BS", name: "Bahamas" },
    { code: "BH", name: "Bahrain" },
    { code: "BD", name: "Bangladesh" },
    { code: "BB", name: "Barbados" },
    { code: "BY", name: "Belarus" },
    { code: "BE", name: "Belgium" },
    { code: "BZ", name: "Belize" },
    { code: "BJ", name: "Benin" },
    { code: "BT", name: "Bhutan" },
    { code: "BO", name: "Bolivia" },
    { code: "BA", name: "Bosnia and Herzegovina" },
    { code: "BW", name: "Botswana" },
    { code: "BR", name: "Brazil" },
    { code: "BG", name: "Bulgaria" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BI", name: "Burundi" },
    { code: "CV", name: "Cabo Verde" },
    { code: "KH", name: "Cambodia" },
    { code: "CM", name: "Cameroon" },
    { code: "CA", name: "Canada" },
    { code: "CF", name: "Central African Republic" },
    { code: "TD", name: "Chad" },
    { code: "CL", name: "Chile" },
    { code: "CN", name: "China" },
    { code: "CO", name: "Colombia" },
    { code: "KM", name: "Comoros" },
    { code: "CG", name: "Congo" },
    { code: "CD", name: "Congo, Democratic Republic of the" },
    { code: "CR", name: "Costa Rica" },
    { code: "CI", name: "Cote d’Ivoire" },
    { code: "HR", name: "Croatia" },
    { code: "CU", name: "Cuba" },
    { code: "CY", name: "Cyprus" },
    { code: "CZ", name: "Czech Republic" },
    { code: "DK", name: "Denmark" },
    { code: "DJ", name: "Djibouti" },
    { code: "DM", name: "Dominica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "EC", name: "Ecuador" },
    { code: "EG", name: "Egypt" },
    { code: "SV", name: "El Salvador" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "EE", name: "Estonia" },
    { code: "SZ", name: "Eswatini" },
    { code: "ET", name: "Ethiopia" },
    { code: "FJ", name: "Fiji" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambia" },
    { code: "GE", name: "Georgia" },
    { code: "DE", name: "Germany" },
    { code: "GH", name: "Ghana" },
    { code: "GR", name: "Greece" },
    { code: "GD", name: "Grenada" },
    { code: "GT", name: "Guatemala" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea Bissau" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haiti" },
    { code: "HN", name: "Honduras" },
    { code: "HU", name: "Hungary" },
    { code: "IS", name: "Iceland" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IR", name: "Iran" },
    { code: "IQ", name: "Iraq" },
    { code: "IE", name: "Ireland" },
    { code: "IL", name: "Israel" },
    { code: "IT", name: "Italy" },
    { code: "JM", name: "Jamaica" },
    { code: "JP", name: "Japan" },
    { code: "JO", name: "Jordan" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KI", name: "Kiribati" },
    { code: "KP", name: "North Korea" },
    { code: "KR", name: "South Korea" },
    { code: "KW", name: "Kuwait" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LV", name: "Latvia" },
    { code: "LB", name: "Lebanon" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libya" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "MY", name: "Malaysia" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MT", name: "Malta" },
    { code: "MH", name: "Marshall Islands" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "MX", name: "Mexico" },
    { code: "FM", name: "Micronesia" },
    { code: "MD", name: "Moldova" },
    { code: "MC", name: "Monaco" },
    { code: "MN", name: "Mongolia" },
    { code: "ME", name: "Montenegro" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "MM", name: "Myanmar" },
    { code: "NA", name: "Namibia" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Nepal" },
    { code: "NL", name: "Netherlands" },
    { code: "NZ", name: "New Zealand" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "MK", name: "North Macedonia" },
    { code: "NO", name: "Norway" },
    { code: "OM", name: "Oman" },
    { code: "PK", name: "Pakistan" },
    { code: "PW", name: "Palau" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papua New Guinea" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Peru" },
    { code: "PH", name: "Philippines" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "QA", name: "Qatar" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russia" },
    { code: "RW", name: "Rwanda" },
    { code: "LC", name: "Saint Lucia" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "WS", name: "Samoa" },
    { code: "SM", name: "San Marino" },
    { code: "ST", name: "Sao Tome and Principe" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SN", name: "Senegal" },
    { code: "RS", name: "Serbia" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SG", name: "Singapore" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "SB", name: "Solomon Islands" },
    { code: "SO", name: "Somalia" },
    { code: "ZA", name: "South Africa" },
    { code: "SS", name: "South Sudan" },
    { code: "ES", name: "Spain" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SD", name: "Sudan" },
    { code: "SR", name: "Suriname" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "SY", name: "Syria" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TZ", name: "Tanzania" },
    { code: "TH", name: "Thailand" },
    { code: "TL", name: "Timor Leste" },
    { code: "TG", name: "Togo" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinidad and Tobago" },
    { code: "TN", name: "Tunisia" },
    { code: "TR", name: "Turkey" },
    { code: "TM", name: "Turkmenistan" },
    { code: "TV", name: "Tuvalu" },
    { code: "UG", name: "Uganda" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "GB", name: "United Kingdom" },
    { code: "US", name: "United States" },
    { code: "UY", name: "Uruguay" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VU", name: "Vanuatu" },
    { code: "VE", name: "Venezuela" },
    { code: "VN", name: "Vietnam" },
    { code: "YE", name: "Yemen" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" }
  ];
  
  export const COUNTRY_CODES_KA = [
    { code: "AF", name: "ავღანეთი" },
    { code: "AL", name: "ალბანეთი" },
    { code: "DZ", name: "ალჟირი" },
    { code: "AD", name: "ანდორა" },
    { code: "AO", name: "ანგოლა" },
    { code: "AG", name: "ანტიგუა და ბარბუდა" },
    { code: "AR", name: "არგენტინა" },
    { code: "AM", name: "სომხეთი" },
    { code: "AU", name: "ავსტრალია" },
    { code: "AT", name: "ავსტრია" },
    { code: "AZ", name: "აზერბაიჯანი" },
    { code: "BS", name: "ბაჰამის კუნძულები" },
    { code: "BH", name: "ბაჰრეინი" },
    { code: "BD", name: "ბანგლადეში" },
    { code: "BB", name: "ბარბადოსი" },
    { code: "BY", name: "ბელარუსი" },
    { code: "BE", name: "ბელგია" },
    { code: "BZ", name: "ბელიზი" },
    { code: "BJ", name: "ბენინი" },
    { code: "BT", name: "ბუტანი" },
    { code: "BO", name: "ბოლივია" },
    { code: "BA", name: "ბოსნია და ჰერცეგოვინა" },
    { code: "BW", name: "ბოტსვანა" },
    { code: "BR", name: "ბრაზილია" },
    { code: "BG", name: "ბულგარეთი" },
    { code: "BF", name: "ბურკინა ფასო" },
    { code: "BI", name: "ბურუნდი" },
    { code: "CV", name: "კაბო ვერდე" },
    { code: "KH", name: "კამბოჯა" },
    { code: "CM", name: "კამერუნი" },
    { code: "CA", name: "კანადა" },
    { code: "CF", name: "ცენტრალური აფრიკის რესპუბლიკა" },
    { code: "TD", name: "ჩადი" },
    { code: "CL", name: "ჩილე" },
    { code: "CN", name: "ჩინეთი" },
    { code: "CO", name: "კოლუმბია" },
    { code: "KM", name: "კომორის კუნძულები" },
    { code: "CG", name: "კონგო" },
    { code: "CD", name: "კონგოს დემოკრატიული რესპუბლიკა" },
    { code: "CR", name: "კოსტა რიკა" },
    { code: "CI", name: "კოტდ’ივუარი" },
    { code: "HR", name: "ხორვატია" },
    { code: "CU", name: "კუბა" },
    { code: "CY", name: "კვიპროსი" },
    { code: "CZ", name: "ჩეხეთი" },
    { code: "DK", name: "დანია" },
    { code: "DJ", name: "ჯიბუტი" },
    { code: "DM", name: "დომინიკა" },
    { code: "DO", name: "დომინიკელთა რესპუბლიკა" },
    { code: "EC", name: "ეკვადორი" },
    { code: "EG", name: "ეგვიპტე" },
    { code: "SV", name: "სალვადორი" },
    { code: "GQ", name: "ეკვატორული გვინეა" },
    { code: "ER", name: "ერიტრეა" },
    { code: "EE", name: "ესტონეთი" },
    { code: "SZ", name: "ესვატინი" },
    { code: "ET", name: "ეთიოპია" },
    { code: "FJ", name: "ფიჯი" },
    { code: "FI", name: "ფინეთი" },
    { code: "FR", name: "საფრანგეთი" },
    { code: "GA", name: "გაბონი" },
    { code: "GM", name: "გამბია" },
    { code: "GE", name: "საქართველო" },
    { code: "DE", name: "გერმანია" },
    { code: "GH", name: "განა" },
    { code: "GR", name: "საბერძნეთი" },
    { code: "GD", name: "გრენადა" },
    { code: "GT", name: "გვატემალა" },
    { code: "GN", name: "გვინეა" },
    { code: "GW", name: "გვინეა ბისაუ" },
    { code: "GY", name: "გაიანა" },
    { code: "HT", name: "ჰაიტი" },
    { code: "HN", name: "ჰონდურასი" },
    { code: "HU", name: "უნგრეთი" },
    { code: "IS", name: "ისლანდია" },
    { code: "IN", name: "ინდოეთი" },
    { code: "ID", name: "ინდონეზია" },
    { code: "IR", name: "ირანი" },
    { code: "IQ", name: "ერაყი" },
    { code: "IE", name: "ირლანდია" },
    { code: "IL", name: "ისრაელი" },
    { code: "IT", name: "იტალია" },
    { code: "JM", name: "იამაიკა" },
    { code: "JP", name: "იაპონია" },
    { code: "JO", name: "იორდანია" },
    { code: "KZ", name: "ყაზახეთი" },
    { code: "KE", name: "კენია" },
    { code: "KI", name: "კირიბატი" },
    { code: "KP", name: "ჩრდილოეთ კორეა" },
    { code: "KR", name: "სამხრეთ კორეა" },
    { code: "KW", name: "ქუვეითი" },
    { code: "KG", name: "ყირგიზეთი" },
    { code: "LV", name: "ლატვია" },
    { code: "LB", name: "ლიბანი" },
    { code: "LS", name: "ლესოთო" },
    { code: "LR", name: "ლიბერია" },
    { code: "LY", name: "ლიბია" },
    { code: "LI", name: "ლიხტენშტაინი" },
    { code: "LT", name: "ლიტვა" },
    { code: "LU", name: "ლუქსემბურგი" },
    { code: "MG", name: "მადაგასკარი" },
    { code: "MW", name: "მალავი" },
    { code: "MY", name: "მალაიზია" },
    { code: "MV", name: "მალდივები" },
    { code: "ML", name: "მალი" },
    { code: "MT", name: "მალტა" },
    { code: "MH", name: "მარშალის კუნძულები" },
    { code: "MR", name: "მავრიტანია" },
    { code: "MU", name: "მავრიკი" },
    { code: "MX", name: "მექსიკა" },
    { code: "FM", name: "მიკრონეზია" },
    { code: "MD", name: "მოლდოვა" },
    { code: "MC", name: "მონაკო" },
    { code: "MN", name: "მონღოლეთი" },
    { code: "ME", name: "მონტენეგრო" },
    { code: "MA", name: "მაროკო" },
    { code: "MZ", name: "მოზამბიკი" },
    { code: "MM", name: "მიანმარი" },
    { code: "NA", name: "ნამიბია" },
    { code: "NR", name: "ნაურუ" },
    { code: "NP", name: "ნეპალი" },
    { code: "NL", name: "ნიდერლანდები" },
    { code: "NZ", name: "ახალი ზელანდია" },
    { code: "NI", name: "ნიკარაგუა" },
    { code: "NE", name: "ნიგერი" },
    { code: "NG", name: "ნიგერია" },
    { code: "MK", name: "ჩრდილოეთ მაკედონია" },
    { code: "NO", name: "ნორვეგია" },
    { code: "OM", name: "ომანი" },
    { code: "PK", name: "პაკისტანი" },
    { code: "PW", name: "პალაუ" },
    { code: "PA", name: "პანამა" },
    { code: "PG", name: "პაპუა ახალი გვინეა" },
    { code: "PY", name: "პარაგვაი" },
    { code: "PE", name: "პერუ" },
    { code: "PH", name: "ფილიპინები" },
    { code: "PL", name: "პოლონეთი" },
    { code: "PT", name: "პორტუგალია" },
    { code: "QA", name: "ყატარი" },
    { code: "RO", name: "რუმინეთი" },
    { code: "RU", name: "რუსეთი" },
    { code: "RW", name: "რუანდა" },
    { code: "LC", name: "სენტ ლუსია" },
    { code: "VC", name: "სენტ ვინსენტი და გრენადინები" },
    { code: "WS", name: "სამოა" },
    { code: "SM", name: "სან მარინო" },
    { code: "ST", name: "სან ტომე და პრინსიპი" },
    { code: "SA", name: "საუდის არაბეთი" },
    { code: "SN", name: "სენეგალი" },
    { code: "RS", name: "სერბეთი" },
    { code: "SC", name: "სეიშელის კუნძულები" },
    { code: "SL", name: "სიერა ლეონე" },
    { code: "SG", name: "სინგაპური" },
    { code: "SK", name: "სლოვაკეთი" },
    { code: "SI", name: "სლოვენია" },
    { code: "SB", name: "სოლომონის კუნძულები" },
    { code: "SO", name: "სომალი" },
    { code: "ZA", name: "სამხრეთ აფრიკა" },
    { code: "SS", name: "სამხრეთ სუდანი" },
    { code: "ES", name: "ესპანეთი" },
    { code: "LK", name: "შრი ლანკა" },
    { code: "SD", name: "სუდანი" },
    { code: "SR", name: "სურინამი" },
    { code: "SE", name: "შვედეთი" },
    { code: "CH", name: "შვეიცარია" },
    { code: "SY", name: "სირია" },
    { code: "TJ", name: "თაჯიკეთი" },
    { code: "TZ", name: "ტანზანია" },
    { code: "TH", name: "ტაილანდი" },
    { code: "TL", name: "აღმოსავლეთ ტიმორი" },
    { code: "TG", name: "ტოგო" },
    { code: "TO", name: "ტონგა" },
    { code: "TT", name: "ტრინიდადი და ტობაგო" },
    { code: "TN", name: "ტუნისი" },
    { code: "TR", name: "თურქეთი" },
    { code: "TM", name: "თურქმენეთი" },
    { code: "TV", name: "ტუვალუ" },
    { code: "UG", name: "უგანდა" },
    { code: "UA", name: "უკრაინა" },
    { code: "AE", name: "არაბთა გაერთიანებული საამიროები" },
    { code: "GB", name: "დიდი ბრიტანეთი" },
    { code: "US", name: "აშშ" },
    { code: "UY", name: "ურუგვაი" },
    { code: "UZ", name: "უზბეკეთი" },
    { code: "VU", name: "ვანუატუ" },
    { code: "VE", name: "ვენესუელა" },
    { code: "VN", name: "ვიეტნამი" },
    { code: "YE", name: "იემენი" },
    { code: "ZM", name: "ზამბია" },
    { code: "ZW", name: "ზიმბაბვე" }
  ];